# Generated by Django 6.0.7 on 2026-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En Cocina'), ('LISTO', 'Plato Listo (Pendiente Cobro)'), ('PAGADO', 'Pagado / Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape / Plin'), ('TRANSFERENCIA', 'Transferencia')], default='PENDIENTE', max_length=20),
        ),
    ]
