# Generated by Django 6.0.7 on 2026-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_orden_estado_alter_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen_alt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
