# Generated by Django 6.0.7 on 2026-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_plato_imagen_alt_plato_imagen_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
