# Generated by Django 6.0.7 on 2026-07-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_detalleorden_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nota_general',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_servicio',
            field=models.CharField(choices=[('MESA', 'En Mesa'), ('LLEVAR', 'Para Llevar')], default='MESA', max_length=20),
        ),
    ]
