# Generated by Django 6.0.7 on 2026-07-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_orden_nota_general_orden_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='es_para_llevar',
            field=models.BooleanField(default=False),
        ),
    ]
