# Generated by Django 6.0.7 on 2026-08-04 05:01

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_categoria_alter_orden_options_plato_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recargo_por_taper', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.plato'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Menú', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus_entrada', to='restaurante.categoria')),
                ('categoria_segundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus_segundo', to='restaurante.categoria')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurante.menu'),
        ),
    ]
