# Generated by Django 6.0.7 on 2026-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_configuracion_alter_detalleorden_plato_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='packable',
            field=models.BooleanField(default=False),
        ),
    ]
