# Generated by Django 6.0.7 on 2026-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_categoria_packable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleorden',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plato__isnull', False), ('menu__isnull', True)), models.Q(('plato__isnull', True), ('menu__isnull', False)), _connector='OR'), name='detalle_orden_exactly_one_plato_or_menu'),
        ),
    ]
