# Generated by Django 6.0.7 on 2026-08-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0010_detalleorden_detalle_orden_exactly_one_plato_or_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='entrada_para_llevar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='segundo_para_llevar',
            field=models.BooleanField(default=False),
        ),
    ]
