# Generated by Django 6.0.7 on 2026-08-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0012_ambiente_mesa_orden_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='alto',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ancho',
            field=models.IntegerField(default=110),
        ),
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('RECTANGULO', 'Rectángulo'), ('CIRCULO', 'Círculo'), ('CUADRADO', 'Cuadrado')], default='RECTANGULO', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_y',
            field=models.IntegerField(default=20),
        ),
    ]
