# Generated by Django 6.0.7 on 2026-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0013_mesa_alto_mesa_ancho_mesa_forma_mesa_posicion_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='modo_envio',
            field=models.CharField(choices=[('KITCHEN', 'Pantalla Cocina'), ('PRINT', 'Impresión')], default='KITCHEN', max_length=10),
        ),
    ]
